--- 

- name: install karmada
  hosts: "{{ gce_host | default('localhost') }}"
  tasks: 
  - name: install package requirements
    yum: 
        name: 
          - git
          - go
        state: present
        update_cache: true
    become: true