--- 

- name: Karmada - install OS prereqs
  hosts: "karmada"
  tasks: 
  - name: install package requirements
    yum: 
        name: 
          - git
          - go
        state: present
        update_cache: true
    become: true
  - name: install kind
    command: go get sigs.k8s.io/kind
    environment:
      PATH:"{{ ansible_env.PATH }}:$(go env GOPATH)/bin"